apiVersion: v1
kind: Pod
metadata:
  name: zero-request
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "0"
      limits:
        cpu: "1000m"
---
apiVersion: v1
kind: Pod
metadata:
  name: normal-pod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"