apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: app-container
    image: nginx:latest
    resources:
      requests:
        cpu: "500m"  # 0.5 CPU cores
        memory: "512Mi"  # 512 Mebibytes
      limits:
        cpu: "1000m"  # 1 CPU core
        memory: "1Gi"  # 1 Gibibyte
  - name: sidecar-container
    image: busybox:latest
    command: ["sh", "-c", "while true; do sleep 30; done"]
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "400m"
        memory: "512Mi"